[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
plonky2 = "1.0.2"
plonky2_crypto = "0.1"

[dev-dependencies]
hex = "0.4"

[patch.crates-io]
plonky2_crypto = { path = "../.." }
